import Footer from "@/components/Footer";
import GeoFeedback from "@/components/GeoFeedback";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-[#03030E]">
      <Header />
      {children}

      <Footer />
    </div>
  );
}
