import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Talk2 from "@/components/Talk2";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CompanyLayout({ children }) {
  return (
    <div>
      {/* <Header /> */}
      {children}
      <Talk2 />
      <Footer />
    </div>
  );
}
